### PR TITLE
Reaping Support

### PR DESCRIPTION
**Pull request by ChrisKader**
Currently I simply have a small icon above each enemy blip on the map to identify what type of reaping mob is spawned. I also added a check for reaping that will remove the data from the blips when the key difficulty is less than 10.

To-do:
- Include reaping counts/data in pull list to identify what mobs will come between pulls at the break points (20/40/60/80/100%)
- Merge current reaping data into existing enemy data structure
- Provide option to show important abilities (interupts, dodges, ect) within tooltip of the mob along with an indicator on the mob blip itself (Maybe a "!").

### CODE REVIEW

**Comment by ChrisKader** [comment]
image

**Comment by ChrisKader** [comment]
The pull request has been updated to include reaping data within the dungeonEnemies table for each dungeon in its respective file.
Code has been updated to reflect updated references and removed references to and copies of ReapingIndex.lua

**Comment by nnogga** [comment]
- Reaping type should be in the bottom of the tooltip and possibly include the icon relevant to the type in the string: https://i.imgur.com/av4OBQr.png
- Frame levels of reaping icons have to be adjusted to not create overlaps with selected enemies: https://i.imgur.com/xlF1laT.png
- Changing the difficulty of the key does not update the visibility state of the reaping icons. Add your check after MethodDungeonTools.lua line 970

**Comment by ChrisKader** [comment]
Updated to resolve issues but I have not added an icon to the reaping line within the tooltip.

**Pull request merged**
